POST  https://wallet1.onrender.com/api/setup
Content-Type: application/json

{
    "balance":10010,
    "name":"new data"
}


###
GET  https://wallet1.onrender.com/api/wallet/63a3db0d21051bc786965153




###
POST  https://wallet1.onrender.com/api/transact/63a3db0d21051bc786965153
Content-Type: application/json

{
    "amount":-10,
    "name":"new data"
}

###
GET  https://wallet1.onrender.com/api/transactions?walletId=63a3db0d21051bc786965153&skip=0&limit=10


###
