POST  https://wallet1.onrender.com/api/setup
Content-Type: application/json

{
    "balance":10010,
    "name":"new data"
}


###
GET  https://wallet1.onrender.com/api/wallet/63a421161f1b0bc216600308




###
POST  https://wallet1.onrender.com/api/transact/63a421161f1b0bc216600308
Content-Type: application/json

{
    "amount":-10,
    "name":"new data"
}

###
GET  https://wallet1.onrender.com/api/transactions?walletId=63a421161f1b0bc216600308&skip=0&limit=10



